version: "3.1"

services:
  db:
    container_name: example
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
    ports:
      - "5432:5432"
